### ISSUE TITLE
Inserting to cache is not thread-safe

### ISSUE THREAD

**Issue by tamasd** [antchfx/htmlquery#19]
I have an application that processes HTML files, heavily parallelized.

I often get panics because the LRU cache tries to add entries to a map at the same time. The offending line is this one: https://github.com/antchfx/htmlquery/blob/master/cache.go#L37

Guarding this with a mutex would solve my issue.

**Comment by zhengchun** [comment]
@tamasd , I had submitted `Mutex` operation, could you test it can works?

**Comment by zhengchun** [comment]
Closed, fixed in Release 1.2.1.

**Comment by tamasd** [comment]
Sorry for the late answer. Unfortunately, I still get this issue with 1.2.1. I get data race errors from tests and invalid results.

**Comment by zhengchun** [comment]
[groupcache/lru#Get](https://github.com/golang/groupcache/blob/a6b377e3400b08991b80d6805d627f347f983866/lru/lru.go#L74) needs to manipulate its list to track recently used item. So remove `read-only` lock and used  `write` lock.

**Comment by zhengchun** [comment]
fixed in v1.2.2

**Comment by tamasd** [comment]
My tests have passed, the bug looks fixed. Thanks!
